name: Build and deploy ASP.Net Core app to Azure Web App - todo-api-abdallah

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish API
        run: dotnet publish ./todo.api/todo.api.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app            # 👈 must match in download
          path: ./publish           # 👈 upload the publish folder

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish           # 👈 download to same folder

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'todo-api-abdallah'   # your App Service name
          slot-name: 'Production'
          package: ./publish              # 👈 deploy the publish folder
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F8939167AC3149D5B6B48242734CBD09 }}
