name: First test Workflow
on: push
jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download .NET 9.0 SDK
      run: |
        curl -L -o dotnet-sdk-9.0.0.tar.gz <https://download.visualstudio.microsoft.com/download/pr/1f3a4f0e-3d6b-4d2e-8f7c-5a5a1c3e6e0b/2b7f6e6c3a4e4b8b9c8e4f6d7a8b9c0d/dotnet-sdk-9.0.0-linux-x64.tar.gz>
        mkdir -p $HOME/dotnet
        tar -zxf dotnet-sdk-9.0.0.tar.gz -C $HOME/dotnet
        echo "$HOME/dotnet" >> $GITHUB_PATH
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal